version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: carbon-components
    versions:
    - 10.26.0
    - 10.28.0
    - 10.29.0
    - 10.31.0
  - dependency-name: react-intl
    versions:
    - 5.10.16
    - 5.12.3
    - 5.13.1
    - 5.13.5
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.3
  - dependency-name: react-redux
    versions:
    - 7.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
